"""add unique constraint on name field in  subcategories table

Revision ID: 328df3679dbe
Revises: 4a7cb3347d37
Create Date: 2026-05-22 13:31:04.935693

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '328df3679dbe'
down_revision: Union[str, Sequence[str], None] = '4a7cb3347d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_subcategories_category_id_name', 'subcategories', ['category_id', 'name']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_subcategories_category_id_name', 'subcategories', type_='unique'
    )
    # ### end Alembic commands ###
