"""add created_at to suppliers

Revision ID: 460ca202ec37
Revises: 0e1273f7ebe4
Create Date: 2026-05-19 15:57:14.764459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460ca202ec37'
down_revision: Union[str, Sequence[str], None] = '0e1273f7ebe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'created_at')
    # ### end Alembic commands ###
