"""set updated_at to non-nullable in products table

Revision ID: 579c91a1d469
Revises: 58fbabd84c6a
Create Date: 2026-05-22 14:42:17.902953

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '579c91a1d469'
down_revision: Union[str, Sequence[str], None] = '58fbabd84c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE products
        SET updated_at = created_at
        WHERE updated_at IS NULL
    """)

    op.alter_column(
        'products', 'updated_at', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products', 'updated_at', existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
