"""set updated_at to non-nullable in subcategories table

Revision ID: 58fbabd84c6a
Revises: f2aeb894c8c1
Create Date: 2026-05-22 14:40:46.788129

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58fbabd84c6a'
down_revision: Union[str, Sequence[str], None] = 'f2aeb894c8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE subcategories
        SET updated_at = created_at
        WHERE updated_at IS NULL
    """)

    op.alter_column(
        'subcategories',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'subcategories',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###
