"""add missing updated_at field to suppliers table

Revision ID: 5bed4334368d
Revises: 532a78676abe
Create Date: 2026-05-22 14:50:32.723692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bed4334368d'
down_revision: Union[str, Sequence[str], None] = '532a78676abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'suppliers',
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
    )

    op.execute("""
        UPDATE suppliers
        SET updated_at = created_at
        WHERE updated_at IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'updated_at')
    # ### end Alembic commands ###
