"""create project_templates and project_template_items tables

Revision ID: 8d41008ddfbc
Revises: 5bed4334368d
Create Date: 2026-05-23 07:25:34.621195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d41008ddfbc'
down_revision: Union[str, Sequence[str], None] = '5bed4334368d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_project_template_name')
    )
    op.create_index(op.f('ix_project_templates_id'), 'project_templates', ['id'], unique=False)
    op.create_table('project_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('parent_template_item_id', sa.Integer(), nullable=True),
    sa.Column('default_name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['parent_template_item_id'], ['project_template_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_template_items_category_id'), 'project_template_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_project_template_items_id'), 'project_template_items', ['id'], unique=False)
    op.create_index(op.f('ix_project_template_items_parent_template_item_id'), 'project_template_items', ['parent_template_item_id'], unique=False)
    op.create_index(op.f('ix_project_template_items_product_id'), 'project_template_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_project_template_items_subcategory_id'), 'project_template_items', ['subcategory_id'], unique=False)
    op.create_index(op.f('ix_project_template_items_template_id'), 'project_template_items', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_template_items_template_id'), table_name='project_template_items')
    op.drop_index(op.f('ix_project_template_items_subcategory_id'), table_name='project_template_items')
    op.drop_index(op.f('ix_project_template_items_product_id'), table_name='project_template_items')
    op.drop_index(op.f('ix_project_template_items_parent_template_item_id'), table_name='project_template_items')
    op.drop_index(op.f('ix_project_template_items_id'), table_name='project_template_items')
    op.drop_index(op.f('ix_project_template_items_category_id'), table_name='project_template_items')
    op.drop_table('project_template_items')
    op.drop_index(op.f('ix_project_templates_id'), table_name='project_templates')
    op.drop_table('project_templates')
    # ### end Alembic commands ###
