"""set updated_at to non-nullable in projects table

Revision ID: 908912a488ce
Revises: 579c91a1d469
Create Date: 2026-05-22 14:46:04.211385

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '908912a488ce'
down_revision: Union[str, Sequence[str], None] = '579c91a1d469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE projects
        SET updated_at = created_at
        WHERE updated_at IS NULL
    """)

    op.alter_column(
        'projects', 'updated_at', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'projects', 'updated_at', existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
