"""create transactions table

Revision ID: af18ade45655
Revises: 3d1d76008700
Create Date: 2026-06-01 11:26:28.826866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af18ade45655'
down_revision: Union[str, Sequence[str], None] = '3d1d76008700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('quote', 'diy_estimate', 'invoice', name='transaction_type'), nullable=False),
    sa.Column('amount_ht', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('amount_vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_ttc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_selected_budget', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("NOT is_selected_budget OR transaction_type IN ('quote', 'diy_estimate')", name='ck_transactions_selected_budget_candidate'),
    sa.CheckConstraint('amount_ht >= 0', name='ck_transactions_amount_ht_positive'),
    sa.CheckConstraint('amount_ttc >= 0', name='ck_transactions_amount_ttc_positive'),
    sa.CheckConstraint('amount_ttc >= amount_ht', name='ck_transactions_ttc_greater_than_ht'),
    sa.CheckConstraint('amount_vat IS NULL OR amount_vat >= 0', name='ck_transactions_amount_vat_positive'),
    sa.CheckConstraint('vat_rate IS NULL OR vat_rate >= 0', name='ck_transactions_vat_rate_positive'),
    sa.ForeignKeyConstraint(['project_item_id'], ['project_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_project_item_id'), 'transactions', ['project_item_id'], unique=False)
    op.create_index(op.f('ix_transactions_supplier_id'), 'transactions', ['supplier_id'], unique=False)
    op.create_index('uq_transactions_project_item_selected_budget', 'transactions', ['project_item_id'], unique=True, postgresql_where=sa.text('is_selected_budget AND deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_transactions_project_item_selected_budget', table_name='transactions', postgresql_where=sa.text('is_selected_budget AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_transactions_supplier_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_project_item_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
