"""add deleted_at to suppliers

Revision ID: d2abb966d37c
Revises: 460ca202ec37
Create Date: 2026-05-20 12:15:39.253123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd2abb966d37c'
down_revision: Union[str, Sequence[str], None] = '460ca202ec37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column(
        'suppliers',
        'comment',
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_unique_constraint('uq_suppliers_name', 'suppliers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_suppliers_name', 'suppliers', type_='unique')
    op.alter_column(
        'suppliers',
        'comment',
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column('suppliers', 'deleted_at')
    # ### end Alembic commands ###
