"""create supplier_documents table

Revision ID: d9a1c3f6b284
Revises: ac6d8cf9146a
Create Date: 2026-07-14 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a1c3f6b284'
down_revision: Union[str, Sequence[str], None] = 'ac6d8cf9146a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_documents_id'), 'supplier_documents', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_documents_supplier_id'), 'supplier_documents', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_documents_user_id'), 'supplier_documents', ['user_id'], unique=False)
    op.create_index(
        'ix_supplier_documents_active_user_created_at',
        'supplier_documents',
        ['user_id', 'created_at'],
        unique=False,
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_supplier_documents_active_user_created_at',
        table_name='supplier_documents',
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    op.drop_index(op.f('ix_supplier_documents_user_id'), table_name='supplier_documents')
    op.drop_index(op.f('ix_supplier_documents_supplier_id'), table_name='supplier_documents')
    op.drop_index(op.f('ix_supplier_documents_id'), table_name='supplier_documents')
    op.drop_table('supplier_documents')
    # ### end Alembic commands ###
