"""set updated_at to non-nullable in categories table

Revision ID: f2aeb894c8c1
Revises: 7d7a965d9016
Create Date: 2026-05-22 14:37:39.030237

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2aeb894c8c1'
down_revision: Union[str, Sequence[str], None] = '7d7a965d9016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE categories
        SET updated_at = created_at
        WHERE updated_at IS NULL
    """)

    op.alter_column(
        'categories', 'updated_at', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'categories', 'updated_at', existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
