table budget_lines_fact
	lineageTag: 88be174c-6ee0-4035-942d-5e6c33adb8ee

	measure 'Nombre de produits' = DISTINCTCOUNT(budget_lines_fact[Produit])
		formatString: 0
		lineageTag: 3db55751-ebe0-431a-af10-22c303dd4314

	measure 'Postes facturés' =
			
			CALCULATE(
			    COUNTROWS(budget_lines_fact),
			    budget_lines_fact[Facturé] = "Oui"
			)
		formatString: 0
		lineageTag: 973fb67a-0b61-4818-8662-642a3e69511a

	measure 'Nombre de postes' = COUNT(budget_lines_fact[Poste de dépense])
		formatString: 0
		lineageTag: 84589d61-1fd2-432d-b490-bf2af9740377

	measure 'Budget moyen par poste' =
			
			AVERAGE(budget_lines_fact[Budget TTC])
		lineageTag: a9dfde35-5084-401c-b855-5b613e806e0f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Coût moyen par poste' =
			
			AVERAGE(budget_lines_fact[Coût réel TTC])
		lineageTag: 29637116-2aa7-42a7-b85e-8fbf4edf23fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ID Projet'
		dataType: int64
		formatString: 0
		lineageTag: cb7f8150-6e84-47ee-976c-043bb1fe7715
		summarizeBy: none
		sourceColumn: ID Projet

		annotation SummarizationSetBy = Automatic

	column Projet
		dataType: string
		lineageTag: 67954dfe-a5fb-4ef1-b71e-40c6f37c8781
		summarizeBy: none
		sourceColumn: Projet

		annotation SummarizationSetBy = Automatic

	column Catégorie
		dataType: string
		lineageTag: 800ec071-ce3f-41fe-a3c5-ff0f09b00834
		summarizeBy: none
		sourceColumn: Catégorie

		annotation SummarizationSetBy = Automatic

	column Sous-catégorie
		dataType: string
		lineageTag: 07bb3347-b11f-44f4-a9bc-bc76694b5bc9
		summarizeBy: none
		sourceColumn: Sous-catégorie

		annotation SummarizationSetBy = Automatic

	column Produit
		dataType: string
		lineageTag: b2a7446f-a279-47f1-9cd8-fe0cefea6293
		summarizeBy: none
		sourceColumn: Produit

		annotation SummarizationSetBy = Automatic

	column 'Budget TTC'
		dataType: double
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 5e8897bc-ef31-4708-9241-0812436b2e22
		summarizeBy: sum
		sourceColumn: Budget TTC

		annotation SummarizationSetBy = Automatic

	column 'Coût réel TTC'
		dataType: double
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 9170429c-325e-4141-a8c5-66b57a1aaa21
		summarizeBy: sum
		sourceColumn: Coût réel TTC

		annotation SummarizationSetBy = Automatic

	column 'Montant payé TTC'
		dataType: double
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 482d592c-c532-45d3-991f-4750ea81af00
		summarizeBy: sum
		sourceColumn: Montant payé TTC

		annotation SummarizationSetBy = Automatic

	column 'Montant impayé TTC'
		dataType: double
		lineageTag: 5730aeff-b6e8-48a0-bcf0-b8d8826c8372
		summarizeBy: sum
		sourceColumn: Montant impayé TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Écart budget TTC'
		dataType: double
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 7536228e-22aa-469b-b942-bf1d505f3a52
		summarizeBy: sum
		sourceColumn: Écart budget TTC

		annotation SummarizationSetBy = Automatic

	column 'Écart budget %'
		dataType: double
		lineageTag: 822830b2-b675-4f40-8983-093308f3ad77
		summarizeBy: sum
		sourceColumn: Écart budget %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nombre de factures'
		dataType: int64
		formatString: 0
		lineageTag: 35e65a39-a004-42fc-b0ee-7fcf328e6b8b
		summarizeBy: sum
		sourceColumn: Nombre de factures

		annotation SummarizationSetBy = Automatic

	column Facturé
		dataType: string
		lineageTag: 2d198f28-f3d4-4b0a-b2a0-0b15983ca6d6
		summarizeBy: none
		sourceColumn: Facturé

		annotation SummarizationSetBy = User

	column 'ID Poste'
		dataType: int64
		formatString: 0
		lineageTag: d4c9a3ad-f873-4498-be68-ec6550482f3f
		summarizeBy: sum
		sourceColumn: ID Poste

		annotation SummarizationSetBy = Automatic

	column 'Poste de dépense'
		dataType: string
		lineageTag: 391e695d-4f2d-4da2-8097-71199fb8c2f0
		summarizeBy: none
		sourceColumn: Poste de dépense

		annotation SummarizationSetBy = Automatic

	partition budget_lines_fact = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("192.168.1.19:5434", "house_building"),
				    analytics_vw_budget_lines_fact = Source{[Schema="analytics",Item="vw_budget_lines_fact"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(analytics_vw_budget_lines_fact,{{"project_id", "ID Projet"}, {"project_name", "Projet"}, {"budget_line_id", "ID Poste"}, {"budget_line_name", "Poste de dépense"}, {"category_name", "Catégorie"}, {"subcategory_name", "Sous-catégorie"}, {"product_name", "Produit"}, {"selected_budget_amount_ttc", "Budget TTC"}, {"actual_amount_ttc", "Coût réel TTC"}, {"paid_amount_ttc", "Montant payé TTC"}, {"unpaid_amount_ttc", "Montant impayé TTC"}, {"variance_ttc", "Écart budget TTC"}, {"variance_pct", "Écart budget %"}, {"invoice_count", "Nombre de factures"}, {"has_invoice", "Facturé"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Facturé", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","0","Non",Replacer.ReplaceText,{"Facturé"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","1","Oui",Replacer.ReplaceText,{"Facturé"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

