table monthly_invoice_activity
	lineageTag: daf23c05-daee-4d8e-b03f-e38fceb39c85

	measure '% Impayé Mensuel' =
			
			
			DIVIDE(
			
			    SUM(monthly_invoice_activity[Montant impayé TTC]),
			
			    SUM(monthly_invoice_activity[Montant payé TTC]),
			
			    0
			
			)
		lineageTag: a9ade35c-535e-4af1-8e82-00779f8a4b11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ID Projet'
		dataType: int64
		formatString: 0
		lineageTag: 3cafcc5b-c87d-4385-9939-e33b0dbe6489
		summarizeBy: none
		sourceColumn: ID Projet

		annotation SummarizationSetBy = Automatic

	column Projet
		dataType: string
		lineageTag: 32501330-7764-4140-929c-02217a648a81
		summarizeBy: none
		sourceColumn: Projet

		annotation SummarizationSetBy = Automatic

	column Mois
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: beafc17d-3e2d-4fec-b573-97e56029d696
		summarizeBy: none
		sourceColumn: Mois

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Montant facturé TTC'
		dataType: double
		lineageTag: e03a48f9-4799-47a5-8448-ca5303ec3b6c
		summarizeBy: sum
		sourceColumn: Montant facturé TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Montant payé TTC'
		dataType: double
		lineageTag: bb3438d6-e1a6-47d6-89c4-a352f1d2a530
		summarizeBy: sum
		sourceColumn: Montant payé TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Montant impayé TTC'
		dataType: double
		lineageTag: a222ae86-8f25-49c4-b22f-a2a884b001f7
		summarizeBy: sum
		sourceColumn: Montant impayé TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cumul facturé TTC'
		dataType: double
		lineageTag: b562d6df-9caf-49b7-9270-1ac34c0555b7
		summarizeBy: sum
		sourceColumn: Cumul facturé TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cumul payé TTC'
		dataType: double
		lineageTag: b30f6933-1a53-46dc-89d4-14916739e62a
		summarizeBy: sum
		sourceColumn: Cumul payé TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cumul impayé TTC'
		dataType: double
		lineageTag: 0d741b3a-89ad-47eb-a911-4538756fe4a6
		summarizeBy: sum
		sourceColumn: Cumul impayé TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition monthly_invoice_activity = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("192.168.1.19:5434", "house_building"),
				    analytics_vw_monthly_invoice_activity = Source{[Schema="analytics",Item="vw_monthly_invoice_activity"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(analytics_vw_monthly_invoice_activity,{{"project_id", "ID Projet"}, {"project_name", "Projet"}, {"month", "Mois"}, {"invoice_amount_ttc", "Montant facturé TTC"}, {"paid_amount_ttc", "Montant payé TTC"}, {"unpaid_amount_ttc", "Montant impayé TTC"}, {"cumulative_invoice_amount_ttc", "Cumul facturé TTC"}, {"cumulative_paid_amount_ttc", "Cumul payé TTC"}, {"cumulative_unpaid_amount_ttc", "Cumul impayé TTC"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

