table monthly_cashflow
	lineageTag: 39e55285-8d69-46e8-bb36-93c30b9a1493

	column 'ID Projet'
		dataType: int64
		formatString: 0
		lineageTag: 7b56dfc6-4ff7-4433-9379-b1adb20acae7
		summarizeBy: none
		sourceColumn: ID Projet

		annotation SummarizationSetBy = Automatic

	column Projet
		dataType: string
		lineageTag: c2ceb634-6ce8-432c-8d37-d50383f91760
		summarizeBy: none
		sourceColumn: Projet

		annotation SummarizationSetBy = Automatic

	column Mois
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 3ba052bf-46a2-45e4-b864-8b79c55e1437
		summarizeBy: none
		sourceColumn: Mois

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Montant payé TTC'
		dataType: double
		lineageTag: d6ad9dea-fd0f-4bce-bcb5-51f41af3202d
		summarizeBy: sum
		sourceColumn: Montant payé TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cumul payé TTC'
		dataType: double
		lineageTag: e66f6e3f-ff38-484e-b702-69c147c81af3
		summarizeBy: sum
		sourceColumn: Cumul payé TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition monthly_cashflow = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("192.168.1.19:5434", "house_building"),
				    analytics_vw_monthly_cashflow = Source{[Schema="analytics",Item="vw_monthly_cashflow"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(analytics_vw_monthly_cashflow,{{"paid_amount_ttc", "Montant payé TTC"}, {"cumulative_paid_amount_ttc", "Cumul payé TTC"}, {"project_id", "ID Projet"}, {"project_name", "Projet"}, {"month", "Mois"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

