table project_summary
	lineageTag: 0b01122f-7ee3-4a3d-ba5b-56c5bc6746c0

	column 'ID Projet'
		dataType: int64
		formatString: 0
		lineageTag: c0573d8d-738f-4763-929b-4edb46cfe38e
		summarizeBy: none
		sourceColumn: ID Projet

		annotation SummarizationSetBy = Automatic

	column Projet
		dataType: string
		lineageTag: 013bf60f-c2d4-4c2e-a060-a6de06500fd9
		summarizeBy: none
		sourceColumn: Projet

		annotation SummarizationSetBy = Automatic

	column Lieu
		dataType: string
		lineageTag: 579be6e7-7e9e-49fa-8108-a50dbd510668
		summarizeBy: none
		sourceColumn: Lieu

		annotation SummarizationSetBy = Automatic

	column 'Date de début'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f8c6741e-7ba0-4ae8-8e3e-251c5c2d426e
		summarizeBy: none
		sourceColumn: Date de début

		variation Variation
			isDefault
			relationship: f9781e7d-e3c8-42dc-9d3b-779ce9611667
			defaultHierarchy: LocalDateTable_2e38923c-b811-42f6-ad55-c9587a9957d0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Date de fin'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 258991bf-4f73-4b8b-8866-6645065afadf
		summarizeBy: none
		sourceColumn: Date de fin

		variation Variation
			isDefault
			relationship: c501ffb5-143d-4f61-87f2-7387e51b7aec
			defaultHierarchy: LocalDateTable_baa884fb-2b73-4333-8c8c-0cec3c9e39ba.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Statut du projet'
		dataType: string
		lineageTag: c22e028d-c2d2-4380-9255-b4ccd4d4641b
		summarizeBy: none
		sourceColumn: Statut du projet

		annotation SummarizationSetBy = Automatic

	column 'Budget TTC'
		dataType: double
		isHidden
		lineageTag: e2b00365-aaf4-4228-b7f1-221a22b05553
		summarizeBy: sum
		sourceColumn: Budget TTC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coût réel TTC'
		dataType: double
		isHidden
		lineageTag: 578b95b4-52c0-438c-afbc-43ee5b5eebea
		summarizeBy: sum
		sourceColumn: Coût réel TTC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Montant payé TTC'
		dataType: double
		isHidden
		lineageTag: 87690a7e-bdd6-4819-b50f-e89284c5b391
		summarizeBy: sum
		sourceColumn: Montant payé TTC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Montant impayé TTC'
		dataType: double
		isHidden
		lineageTag: fcc883d3-033b-4cab-bbd9-64ef7c08655a
		summarizeBy: sum
		sourceColumn: Montant impayé TTC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Écart budget TTC'
		dataType: double
		isHidden
		lineageTag: 3161edbd-1da2-4368-b07e-97591a7323b8
		summarizeBy: sum
		sourceColumn: Écart budget TTC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Écart budget %'
		dataType: double
		isHidden
		lineageTag: 2344b446-5d74-496d-bae6-662b2b4cf6a8
		summarizeBy: sum
		sourceColumn: Écart budget %

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Budget consommé %'
		dataType: double
		isHidden
		lineageTag: 68680790-14a2-4ef9-94d6-95f96f00383e
		summarizeBy: sum
		sourceColumn: Budget consommé %

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nombre de fournisseurs'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cddf3286-0210-4147-b1dd-e31eb6cafbcf
		summarizeBy: sum
		sourceColumn: Nombre de fournisseurs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Nombre de postes'
		dataType: int64
		formatString: 0
		lineageTag: 39f088ad-2af6-49a7-b8a2-c01255db774b
		summarizeBy: sum
		sourceColumn: Nombre de postes

		annotation SummarizationSetBy = Automatic

	column 'Nombre de factures'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d042586a-92ed-4cf8-bf20-f614759a60a3
		summarizeBy: sum
		sourceColumn: Nombre de factures

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition project_summary = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("192.168.1.19:5434", "house_building"),
				    analytics_vw_project_summary = Source{[Schema="analytics",Item="vw_project_summary"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(analytics_vw_project_summary,{{"location", "Lieu"}, {"project_id", "ID Projet"}, {"project_name", "Projet"}, {"project_status", "Statut du projet"}, {"start_date", "Date de début"}, {"end_date", "Date de fin"}, {"total_selected_budget_ttc", "Budget TTC"}, {"total_actual_ttc", "Coût réel TTC"}, {"total_paid_ttc", "Montant payé TTC"}, {"total_unpaid_ttc", "Montant impayé TTC"}, {"total_variance_ttc", "Écart budget TTC"}, {"actual_vs_budget_pct", "Budget consommé %"}, {"supplier_count", "Nombre de fournisseurs"}, {"project_item_count", "Nombre de postes"}, {"invoice_count", "Nombre de factures"}, {"total_variance_pct", "Écart budget %"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

