table transactions_fact
	lineageTag: 95730015-8400-4211-9d85-eba6c49983a0

	column 'ID Transaction'
		dataType: int64
		formatString: 0
		lineageTag: 1a95b821-50c7-4d39-a4ab-92e6c904c209
		summarizeBy: none
		sourceColumn: ID Transaction

		annotation SummarizationSetBy = User

	column 'ID Projet'
		dataType: int64
		formatString: 0
		lineageTag: 6668a28b-75a0-431b-a8e8-7af577ee1a74
		summarizeBy: none
		sourceColumn: ID Projet

		annotation SummarizationSetBy = Automatic

	column Projet
		dataType: string
		lineageTag: ac17e4ce-6d58-482d-b37e-5dcafa6beca1
		summarizeBy: none
		sourceColumn: Projet

		annotation SummarizationSetBy = Automatic

	column 'ID Fournisseur'
		dataType: int64
		formatString: 0
		lineageTag: 54e32434-8450-41d4-9d8d-8d8aa28fdd09
		summarizeBy: none
		sourceColumn: ID Fournisseur

		annotation SummarizationSetBy = User

	column Fournisseur
		dataType: string
		lineageTag: 6667ff48-c95f-40a7-bac5-bc11a0f6b51a
		summarizeBy: none
		sourceColumn: Fournisseur

		annotation SummarizationSetBy = Automatic

	column Catégorie
		dataType: string
		lineageTag: 0dd49cd4-9714-4ea1-80f7-50479a8005f4
		summarizeBy: none
		sourceColumn: Catégorie

		annotation SummarizationSetBy = Automatic

	column Sous-catégorie
		dataType: string
		lineageTag: 28aa12f9-b52e-438a-a975-d9beb350c5c8
		summarizeBy: none
		sourceColumn: Sous-catégorie

		annotation SummarizationSetBy = Automatic

	column Produit
		dataType: string
		lineageTag: 667bf83d-90e1-45fc-b9a8-cf32f2cd86d4
		summarizeBy: none
		sourceColumn: Produit

		annotation SummarizationSetBy = Automatic

	column 'Type de transaction'
		dataType: string
		lineageTag: 78ad91e1-2a24-4cef-ac39-88e8d953d54d
		summarizeBy: none
		sourceColumn: Type de transaction

		annotation SummarizationSetBy = Automatic

	column 'Statut devis'
		dataType: string
		lineageTag: 80e2f2e7-32e7-4ca0-8a8d-922833bac75c
		summarizeBy: none
		sourceColumn: Statut devis

		annotation SummarizationSetBy = Automatic

	column 'Statut facture'
		dataType: string
		lineageTag: bd7834cf-b082-43fa-a7d0-9d26ddea2674
		summarizeBy: none
		sourceColumn: Statut facture

		annotation SummarizationSetBy = Automatic

	column 'Budget sélectionné'
		dataType: string
		lineageTag: 94199af8-091a-4948-9053-35cb513f89de
		summarizeBy: none
		sourceColumn: Budget sélectionné

		annotation SummarizationSetBy = Automatic

	column 'Montant HT'
		dataType: double
		lineageTag: eb536cf0-b5a8-495f-ac27-1e56a176d7fe
		summarizeBy: sum
		sourceColumn: Montant HT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TVA
		dataType: double
		lineageTag: 794b63f6-687b-42c5-b312-46e844e2af9b
		summarizeBy: sum
		sourceColumn: TVA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Montant TTC'
		dataType: double
		lineageTag: 6408f8c5-41e7-480a-8384-53ba31125d24
		summarizeBy: sum
		sourceColumn: Montant TTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date d’émission'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e66795db-3ad5-492d-b297-e54d711b2a2d
		summarizeBy: none
		sourceColumn: Date d’émission

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Date d’échéance'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 060c1742-f0b1-41ac-8b13-9274fed22945
		summarizeBy: none
		sourceColumn: Date d’échéance

		variation Variation
			isDefault
			relationship: b8689cc7-57ea-4c39-a8fd-91a2e1bca5de
			defaultHierarchy: LocalDateTable_c3c54200-3c0c-47ac-ad21-e820947f7f08.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Date de paiement'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e42889eb-e5c1-4409-94a7-a655ef089b8e
		summarizeBy: none
		sourceColumn: Date de paiement

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Retard brut (jours)'
		dataType: int64
		formatString: 0
		lineageTag: b1bfe41c-8ccd-4828-8fac-cec1fc091d76
		summarizeBy: sum
		sourceColumn: Retard brut (jours)

		annotation SummarizationSetBy = Automatic

	column 'Retard paiement (jours)'
		dataType: int64
		formatString: 0
		lineageTag: e63bebd8-c50e-4c4a-90d1-6dd7dc68690b
		summarizeBy: sum
		sourceColumn: Retard paiement (jours)

		annotation SummarizationSetBy = Automatic

	column 'Paiement en retard'
		dataType: string
		lineageTag: 8c318c72-f43d-4e72-a7c3-072d6ab5f0ec
		summarizeBy: none
		sourceColumn: Paiement en retard

		annotation SummarizationSetBy = Automatic

	column 'ID Poste'
		dataType: int64
		formatString: 0
		lineageTag: 7414f74e-2f0a-4e61-8740-de14e6700aeb
		summarizeBy: sum
		sourceColumn: ID Poste

		annotation SummarizationSetBy = Automatic

	column 'Poste de dépense'
		dataType: string
		lineageTag: a465dde7-b8c1-4b8e-b326-ba447c028b1b
		summarizeBy: none
		sourceColumn: Poste de dépense

		annotation SummarizationSetBy = Automatic

	partition transactions_fact = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("192.168.1.19:5434", "house_building"),
				    analytics_vw_transactions_fact = Source{[Schema="analytics",Item="vw_transactions_fact"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(analytics_vw_transactions_fact,{{"transaction_id", "ID Transaction"}, {"project_id", "ID Projet"}, {"budget_line_id", "ID Poste"}, {"project_name", "Projet"}, {"supplier_id", "ID Fournisseur"}, {"budget_line_name", "Poste de dépense"}, {"supplier_name", "Fournisseur"}, {"category_name", "Catégorie"}, {"subcategory_name", "Sous-catégorie"}, {"product_name", "Produit"}, {"transaction_type", "Type de transaction"}, {"quote_status", "Statut devis"}, {"invoice_status", "Statut facture"}, {"is_selected_budget", "Budget sélectionné"}, {"amount_ht", "Montant HT"}, {"amount_vat", "TVA"}, {"amount_ttc", "Montant TTC"}, {"issued_date", "Date d’émission"}, {"due_date", "Date d’échéance"}, {"payment_date", "Date de paiement"}, {"payment_delay_days_raw", "Retard brut (jours)"}, {"payment_delay_days", "Retard paiement (jours)"}, {"is_late_payment", "Paiement en retard"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Paiement en retard", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","0","Non",Replacer.ReplaceText,{"Paiement en retard"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","1","Oui",Replacer.ReplaceText,{"Paiement en retard"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","quote","Devis",Replacer.ReplaceText,{"Type de transaction"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","invoice","Facture",Replacer.ReplaceText,{"Type de transaction"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","diy_estimate","Estimation DIY",Replacer.ReplaceText,{"Type de transaction"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","to_confirm","À confirmer",Replacer.ReplaceText,{"Statut devis"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value5","unpaid","Impayée",Replacer.ReplaceText,{"Statut facture"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value7","validated","Validé",Replacer.ReplaceText,{"Statut devis"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value6","paidImpayée","Payée",Replacer.ReplaceText,{"Statut facture"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","paid","Payée",Replacer.ReplaceText,{"Statut facture"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value9",{{"Budget sélectionné", type text}}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Changed Type1","true","Oui",Replacer.ReplaceText,{"Budget sélectionné"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","false","Non",Replacer.ReplaceText,{"Budget sélectionné"})
				in
				    #"Replaced Value11"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

